const QUESTIONS = [
  {
    id: 2,
    question: 'What is the emission designation for VHF-FM?',
    answers: ['F3C', 'J2B', 'F3E', 'G2B'],
    correct: 2,
  },
  {
    id: 13,
    question: 'The correct mode of emission for HF radiotelephony SSB transmission is',
    answers: ['J3E', 'H3E', 'F1B', 'G3E'],
    correct: 0,
  },
  {
    id: 64,
    question: 'What is the emission designation for MF-HF voice signals?',
    answers: ['F1B', 'J3E', 'J2B', 'F3E'],
    correct: 1,
  },
  {
    id: 68,
    question: 'Which emission mode occupies the most bandwidth?',
    answers: ['J2B', 'J3E', 'F1B', 'F3E'],
    correct: 3,
  },
  {
    id: 69,
    question: 'Which mode occupies the least bandwidth?',
    answers: ['H3E', 'J2B', 'G3E', 'F3E'],
    correct: 1,
  },
  {
    id: 70,
    question: 'What is the emission designation for MF-HF voice signals?',
    answers: ['F1B', 'J3E', 'J2B', 'F3E'],
    correct: 1,
  },
  {
    id: 118,
    question: 'The Radio Telex mode to be used when broadcasting a Distress Message, on 2174.5kHz, is:',
    answers: ['J3E', 'ARQ', 'H3E', 'FEC'],
    correct: 3,
  },
  {
    id: 122,
    question: 'The correct mode of emission for a RT distress message on 2182 kHz is',
    answers: ['R3E', 'F1B', 'H3E', 'J3E'],
    correct: 2,
  },
  {
    id: 123,
    question: 'The correct class of emission for a MF Radiotelex transmission is',
    answers: ['F1B', 'J3E', 'G3E', 'F3E'],
    correct: 0,
  },
  {
    id: 124,
    question: 'The mode of emission used for voice on MF and HF is',
    answers: ['F3E', 'A3E', 'J3E', 'F1B'],
    correct: 2,
  },
  {
    id: 125,
    question: 'The Radio Telex mode to be used for one-to-one communications, with automatic error correction, is:',
    answers: ['H3E', 'ARQ', 'J3E', 'FEC'],
    correct: 1,
  },
  {
    id: 197,
    question: 'The abbreviation of telephony mode of radiation using phase modulation is',
    answers: ['F1B', 'F3E', 'G3E', 'P3E'],
    correct: 2,
  },
  {
    id: 198,
    question: 'The abbreviation of telephony mode of radiation using amplitude modulation, SSB, suppressed carrier is',
    answers: ['A3E', 'J3E', 'H3E', 'J2B'],
    correct: 1,
  },
  {
    id: 199,
    question: 'The abbreviation of telephony mode of radiation using amplitude modulation, SSB, full carrier is',
    answers: ['A3E', 'J3E', 'H3E', 'J2B'],
    correct: 2,
  },
  {
    id: 202,
    question: 'Which type of transmission is used for transmitting ARQ and FEC from Ship Radio Station?',
    answers: ['G3E', 'H3E', 'J2B', 'SSB GMDSS'],
    correct: 2,
  },
  {
    id: 203,
    question: 'Which type of transmission is used for transmitting USB MF/HF call?',
    answers: ['F3E', 'J3E', 'G2B', 'VHF Radiotelephony'],
    correct: 1,
  },
  {
    id: 376,
    question: 'VHF-DSC transmissions are encoded and transmitted in what emission mode?',
    answers: ['H3E', 'F1B/J2B', 'A3E', 'None of these'],
    correct: 1,
  },
];
